server:
  port: 8080
  mode: debug  # debug or release

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456
  dbname: virtual_campus_tour
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

email:
  host: smtp.qq.com  # QQ邮箱SMTP服务器地址
  port: 587         # QQ邮箱SMTP服务器端口
  username: virtual_sysu_tour@qq.com  # 你的QQ邮箱地址
  password: kfiwtbgxpuencdgi  # 你的QQ邮箱授权码（不是QQ密码）
  from: virtual_sysu_tour@qq.com  # 发件人邮箱（同username）

test:
  database:
    password: ${database.password}  # 使用与主数据库相同的密码
    dbname: virtual_campus_tour_test  # 测试专用数据库名

# jwt:
#   secret: your-secret-key
#   expire: 24h  # token expiration time 